---
- name: FreeBSD | Install Apache24
  community.general.pkgng:
    name: apache24
    state: latest
  notify: Restart FreeBSD Apache

- name: FreeBSD | Enable Apache24
  ansible.builtin.service:
    name: apache24
    enabled: true
    state: started
  notify: Restart FreeBSD Apache
