---
- name: Ubuntu | Install Apache2
  ansible.builtin.apt:
    name: apache2
    state: latest

- name: Ubuntu | Enable Apache2
  ansible.builtin.service:
    name: apache2
    enabled: true
    state: started
  notify: Restart apache

#- name: Ubuntu | Install msmtp configuration file
#  ansible.builtin.template:
#    src: msmtprc.j2
#    dest: /etc/msmtprc
#    owner: root
#    group: msmtp
#   mode: '0640'
#   backup: true
